# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PY-0uFx6AvX8ui1vUhp5X0fPcs4-7plY
"""

# Commented out IPython magic to ensure Python compatibility.
// Turjo 86 ; 12/03/2019
 
# %matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (20.0, 10.0)
 

data = pd.read_csv('train.csv')
print(data.shape)
data.head()
 
 

X = data['x'].values
Y = data['y'].values

mean_x = np.mean(X)
mean_y = np.mean(Y)

n = len(X)
print(n)
 

na = 0
da = 0
for i in range(n):

 na += (X[i] - mean_x) * (Y[i] - mean_y)
 da += (X[i] - mean_x) ** 2
 m = na/da
 c = mean_y - (m * mean_x)
 

print(m, c)

max_x = np.max(X) + 100
min_x = np.min(X) - 100

x = np.linspace(min_x, max_x, 1000)
y = c + m * x 
 
# Ploting Line
plt.plot(x, y, color='#52b920', label='Regression Line')
# Ploting Scatter Points
plt.scatter(X, Y, c='#ef4423', label='Scatter Plot')
 
plt.xlabel('Head Size in cm3')
plt.ylabel('Brain Weight in grams')
plt.legend()
plt.show()